// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv4OWNP1BgKOTw4EvI2-l2PMctNKhtNWU',
    appId: '1:525584307325:web:0329b81913b931611b0d14',
    messagingSenderId: '525584307325',
    projectId: 'bart-app-a79ac',
    authDomain: 'bart-app-a79ac.firebaseapp.com',
    storageBucket: 'bart-app-a79ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaakM2GpjR6MUUpp-BWqvja1auTYt82kk',
    appId: '1:525584307325:android:da49dfc8dda69dd01b0d14',
    messagingSenderId: '525584307325',
    projectId: 'bart-app-a79ac',
    storageBucket: 'bart-app-a79ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeRKxJWB0AfLgfxC7emJ0PH84BQsDsvTg',
    appId: '1:525584307325:ios:69e1cb79699d18001b0d14',
    messagingSenderId: '525584307325',
    projectId: 'bart-app-a79ac',
    storageBucket: 'bart-app-a79ac.appspot.com',
    androidClientId: '525584307325-avlbvfd1s93mopr1crf1ait55du2o8ck.apps.googleusercontent.com',
    iosClientId: '525584307325-1dknuudb72voh2k2m75ta9tl4vbueod0.apps.googleusercontent.com',
    iosBundleId: 'com.bart.trade.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeRKxJWB0AfLgfxC7emJ0PH84BQsDsvTg',
    appId: '1:525584307325:ios:69e1cb79699d18001b0d14',
    messagingSenderId: '525584307325',
    projectId: 'bart-app-a79ac',
    storageBucket: 'bart-app-a79ac.appspot.com',
    androidClientId: '525584307325-avlbvfd1s93mopr1crf1ait55du2o8ck.apps.googleusercontent.com',
    iosClientId: '525584307325-1dknuudb72voh2k2m75ta9tl4vbueod0.apps.googleusercontent.com',
    iosBundleId: 'com.bart.trade.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv4OWNP1BgKOTw4EvI2-l2PMctNKhtNWU',
    appId: '1:525584307325:web:0329b81913b931611b0d14',
    messagingSenderId: '525584307325',
    projectId: 'bart-app-a79ac',
    authDomain: 'bart-app-a79ac.firebaseapp.com',
    storageBucket: 'bart-app-a79ac.appspot.com',
  );

}